name: Issue Template Bot

on:
  issues:
    types: [opened, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Bot
        uses: ./.github/actions/issue_template_bot
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          config_path: ".github/issue_template_bot.json"